---
title: "Bloomingdales Spider"
author: "Michael Muller"
date: "April 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(stringr)
library(jsonlite)
library(devtools)
library(httr)
library(Rcpp)
library(dplyr)
library(knitr)
options(digits = 4)
options(stringsAsFactors = FALSE)
```

```{r}

dataMissing = function(x){
  if(length(x)== 0 | is.null(x))
    return(NA)
  else{
    return(x)
  }
}

viableMaterials = c('charmeuse','cotton','polyamide','polyester','satin','silk','spandex','velvet','tactel','viscose','nylon','microfiber','chiffon','elastane','elastic','jacquard','leather','lycra','merino','wool','combed','mesh','knit','fabric', 'woven')
viableStyles = c('briefs','boxer briefs','trunks','boxers','underwear','thong','g-string','boxer short','bikini')


#Here is all 283 listings of all male under-garments at bloomingdales
bloomingdalesURLS = c('https://www.bloomingdales.com/shop/mens/underwear-boxers-briefs-trunks/Underwear_type,Productsperpage/Boxer%20Brief%7CBoxer%7CBrief%7CJockstrap%2FThong%7CTrunk,180?id=1006225',
                      'https://www.bloomingdales.com/shop/mens/underwear-boxers-briefs-trunks/Underwear_type,Pageindex,Productsperpage/Boxer%7CBoxer%20Brief%7CBrief%7CJockstrap%2FThong%7CTrunk,2,180?id=1006225')
allImportantLinks = c() #Populating in below loop

for(url in bloomingdalesURLS){
bloomingdalesHTML = read_html(url)

  nodes = html_nodes(bloomingdalesHTML,"li") 
  nodes = html_nodes(nodes,"div")
  nodes = html_nodes(nodes,"a")
  links = html_attr(nodes,'href')
  allLinks = as.character(links[seq(68,length(links),3)])
  allLinks = allLinks[str_detect(allLinks,'pack')==FALSE]
  allLinks = allLinks[str_detect(allLinks,'set')==FALSE]
  allImportantLinks = c(allImportantLinks,allLinks[6:length(allLinks)])
}
#results = list(1:length(allImportantLinks))
results = list()
count = 1


#exampleLinkHTML = read_html(allLinks[15])

for(L in allImportantLinks){
  url = paste0(L)
  lines = readLines("./custom_scrape.js")
  lines[1] = paste0("var url ='", url ,"';")
  writeLines(lines, "custom_scrape.js")
  
system('./phantomjs  custom_scrape.js')
pg <- read_html("loaded.html")


original_price = html_nodes(pg,xpath='//*[@id="orgPrice"]/span[2]')
print(original_price)
bullet_points = html_nodes(pg,xpath = '//*[@class="product-details-bullet-list"]')
title = html_nodes(pg,xpath = '//*[@id="productName"]')
rating = html_nodes(pg,xpath = '//*[@id="BVRRRatingOverall_Rating_Summary_1"]/div[2]/img')
sale = html_nodes(pg,xpath = '//*[@id="salePrice"]/span[2]')
color = html_nodes(pg,xpath = '//*[@id="colors_0"]/div[1]/ul')



colors = dataMissing(unique(unlist(str_extract_all(as.character(color),'(?<=alt=")[[:alpha:] [:alpha:]]+(?=")',simplify = FALSE))))
original_price = dataMissing(str_extract(as.character(original_price),'[0-9]+.[0-9]{2}'))
sale = dataMissing(str_extract(as.character(sale),'[0-9]+.[0-9]{2}'))
title = str_replace_all(as.character(title),'-',' ')
title = dataMissing(unlist(str_extract_all(as.character(title),'(?<=name">)[[:alpha:] ]*(?=<)')))
bullet_points = dataMissing(str_extract_all(as.character(bullet_points),'(?<=li>)[[:alpha:] /[:alpha:]]*(?=<)'))
rating = dataMissing(str_extract(as.character(rating), '[1-5] (?=/)' ))
materials = dataMissing(unlist(str_extract_all(tolower(bullet_points),viableMaterials)))
style = dataMissing(unlist(str_extract_all(tolower(title),viableStyles)))

print(L)
observation = list(style,title,colors,materials,original_price,sale,rating,'bloomingdales')


results[[count]] = observation
count = count +1
}

bloomingdalesResults = as.data.frame(do.call(cbind, results))
bloomingdalesResults = data.frame(lapply(bloomingdalesResults, as.character), stringsAsFactors=FALSE)
```



```{r}

```

```{r eval=FALSE}
colors = unique(unlist(str_extract_all(as.character(color),'(?<=alt=")[[:alpha:] [:alpha:]]+(?=")',simplify = FALSE)))
original_price = str_extract(as.character(original_price),'[0-9]+.[0-9]{2}')
sale = str_extract(as.character(sale),'[0-9]+.[0-9]{2}')
title = str_extract(as.character(title),'(?<=name">)[[:alpha:] ]*(?=<)')
bullet_points = str_extract_all(as.character(bullet_points),'(?<=li>)[[:alpha:] /[:alpha:]]*(?=<)')
review = str_extract(as.character(review), '[1-5] (?=/)' )
materials = unlist(str_extract_all(tolower(bullet_points),viableMaterials))
style = unlist(str_extract_all(tolower(title),viableStyles))

```
```{r}
patterns = function(x){
  print(x)
  if(x == "NA")
    return('pattern')
  else{return(x)}
}


bloomingdalesResults[3,] = lapply(bloomingdalesResults[3,],patterns)
write.csv2(bloomingdalesResults,'bloomingdales.csv')
```



#str_extract(x,'(?<=-)[1-9]+?')
